IF EXISTS(SELECT 1 FROM SYSOBJECTS WHERE [Name] = 'FI_SP_PesqBeneficiario' AND [type] = 'P')
BEGIN
    DROP PROCEDURE [dbo].[FI_SP_PesqBeneficiario]
	PRINT 'Procedure FI_SP_PesqBeneficiario foi descartado.'
END
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE PROC FI_SP_PesqBeneficiario
	@IDCLIENTE BIGINT
AS
BEGIN
	IF(ISNULL(@IDCLIENTE,0) = 0)
		SELECT CPF, NOME, IDCLIENTE, ID FROM BENEFICIARIOS WITH(NOLOCK)
	ELSE
		SELECT CPF, NOME, IDCLIENTE, ID FROM BENEFICIARIOS WITH(NOLOCK) WHERE IDCLIENTE = @IDCLIENTE
END


GO

PRINT 'Procedure FI_SP_PesqBeneficiario foi criado.'

GO