IF NOT EXISTS(SELECT 1 FROM SYSCOLUMNS WHERE [Name] = 'CPF' AND [Id] = OBJECT_ID(N'CLIENTES'))
BEGIN
	ALTER TABLE [CLIENTES]
		ADD [CPF] VARCHAR(14) NOT NULL

	PRINT 'Coluna CPF foi adicionado à tabela CLIENTES.'
END
ELSE
	PRINT 'Coluna CPF JÁ EXISTE na tabela CLIENTES.'
GO
